### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by AndersSpringborg** [aau-datsw/ruslan-csgo#2]
Tell how to load a match, when the server is running
See `rcon get5_loadmatch match.json`as example

**Comment by frederikspang** [comment]
Jeg tager et kig på denne ifbm. lan weekend @AndersSpringborg

**Comment by frederikspang** [comment]
Jeg har glemt at tage et kig på den her ifbm. lan weekend @AndersSpringborg

**Comment by AndersSpringborg** [comment]
Hahahahah, jeg venter stadig sygt spændt

**Comment by AndersSpringborg** [comment]
Jeg tror vi har droppet det her repo, da det har været så billigt at købe nogle ved [dat hosting](https://dathost.net/)

**Comment by frederikspang** [comment]
Så lukker vi sgu bare den her
